# Generated by Django 4.2.6 on 2023-11-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero_seguimiento',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
