# Generated by Django 4.2.6 on 2023-11-19 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0004_alter_pedido_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='total',
            new_name='monto_total',
        ),
    ]
