# Generated by Django 4.2.6 on 2023-11-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0005_rename_total_pedido_monto_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='monto_total',
        ),
        migrations.AddField(
            model_name='pedido',
            name='rut_cliente',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
