# Generated by Django 4.2.6 on 2023-11-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0006_remove_pedido_monto_total_pedido_rut_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='rut_cliente',
        ),
        migrations.AddField(
            model_name='pedido',
            name='rut',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
