# Generated by Django 4.2.6 on 2023-11-19 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0007_remove_pedido_rut_cliente_pedido_rut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='rut',
        ),
    ]
